.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. najafbit_qt test_najafbit_qt
clean: FORCE
	$(MAKE) -C .. najafbit_qt_clean test_najafbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_najafbit_qt_check
najafbit-qt najafbit-qt.exe: FORCE
	 $(MAKE) -C .. najafbit_qt
